---
# - name: Log into ECR if required.
#   shell: "$(aws ecr get-login --no-include-email --region {{ ecr_region }})"
#   tags: ['skip_ansible_lint']
#   when: ecr_push or ecr_login_required

# @see https://github.com/geerlingguy/ansible-role-ecr_container_build/issues/15
- name: Log into ECR if required.
  shell: |
    aws ecr get-login-password --region {{ ecr_region }} | \
      docker login --username AWS --password-stdin {{ ecr_url }}
  tags: ['skip_ansible_lint']
  when: ecr_push or ecr_login_required

- name: Build image.
  docker_image:
    build:
      path: "{{ ecr_image_src_dir }}"
      pull: true
      args: "{{ ecr_image_buildargs | default(omit) }}"
      network: host
    name: "{{ ecr_image_name }}"
    state: present
    source: build
    tag: "{{ ecr_image_tags.0 }}"
  async: 3600
  poll: 0
  register: build_image_sleeper

- name: Wait for image build to complete.
  include_tasks: wait-docker-until-success.yml
  vars:
    wait_block_name: "Wait for image build to complete [{{ ecr_image_name }}]"
    results_file: "{{ build_image_sleeper.results_file }}"

- name: Ensure ECR repo exists.
  ecs_ecr:
    name: "{{ ecr_image_name }}"
    region: "{{ ecr_region }}"
    registry_id: "{{ ecr_account_id }}"
    state: present
  when: ecr_push

- name: Tag and push the image.
  include_tasks: tag-and-push.yml
  loop: "{{ ecr_image_tags }}"
  loop_control:
    loop_var: outer_item
  when: ecr_push
